# List of backgrounds that you can change to
Backgroundlist = [
	"Anime",
	"basement",
	"birthday",
	"blackout",
	"christmas",
	"classtrial",
	"cofe",
	"cruise",
	"default",
	"defendantlobby",
	"DGSenglishcourt2",
	"dungeon",
	"endless",
	"gray",
	"gs4",
	"gs4night",
	"gs5",
	"japanese",
	"Kurain",
	"plvsaa",
	"RuinedCourt",
	"sky",
	"Spaceship",
	"Themis",
	"Turnabout",
	"whitedoor",
	"whiteroom",
	"zetta",
]