# cannot contain more than 100 characters

Charlist = [
# page 1, first half
	"Phoenix",
	"Layton",
	"Young Mia",
	"Apollo",
	"Birdman",
	"Ryunosuke Naruhodo",
	"Athena",
	"AAI-YoungFranziska",
	"AAI Gregory",
	"Raymond Shields",
# page 1, second half
	"Kay",
	"Holmes",
	"Shimon",
	"Wocky Kitaki",
	"Tsukasa",
	"Miles",
	"Godot",
	"Manfred",
	"Itami_Muto",
	"Robin Newman",
# page 2, first half
	"Portsman",
	"Long Lang",
	"Gina Lestrade",
	"Klavier",
	"Franziska",
	"Bansai Dragons",
	"Quercus Alba",
	"Sebastian",
	"Simon Clown",
	"Ryouken Hoinbo",
# page 2, second half
	"Hawk",
	"Blackquill",
	"Fulbright",
	"Teikan Dragons",
	"Zinc Lablanc",
	"Colias Palaeno",
	"Kazuma",
	"Hakari",
	"Cammy",
	"Rhoda Teneiro",
# page 3, first half
	"Gumshoe",
	"Kristoph G",
	"Yew",
	"Adrian",
	"Daryan Crescend",
	"Butz",
	"Atmey",
	"Lauren Paups",
	"Gant",
	"Lana",
# page 3, second half
	"Marshall",
	"Matt",
	"Wesley Stickler",
	"Neil",
	"Guy",
	"Maya",
	"Lance Amano",
	"EmaSkye",
	"Barok Z",
	"Maggey",
# page 4, first half
	"Max Payne",
	"Oldbag",
	"Trucy",
	"Wellington",
	"Cabanela",
	"Vera",
	"Valant",
	"Leifa Padma Kurain",
	"Shih-na",
	"April",
# page 4, second half
	"AAI Shelly",
	"Pearl",
	"Furio",
	"Max",
	"Meekins",
	"Moe",
	"Barnham",
	"Ron",
	"Means",
	"Sahwit",
# page 5, first half
	"Vasquez",
	"Tyrell Badd",
	"White",
	"WillP",
	"Yanni",
	"Dahlia",
	"Caeser Villan",
	"Olga Orly",
	"Darklaw",
	"Yutaka",
# page 5, second half
	"Jay Elbird",
	"Adachi",
	"Angel Starr",
	"Knightley",
	"Judge ET",
	"Judge's Bro",
	"1 Anonymous",
	"2 Anonymous",
	"3 Anonymous",
	"4 Anonymous",
]