# cannot contain more than 100 characters

Charlist = [
# page 1, first half
	"Phoenix",
	"Young Mia",
	"Apollo",
	"AAI Gregory",
	"Yew",
	"Raymond Shields",
	"Layton",
	"Athena",
    "Ryunosuke Naruhodo",
    "Kazuma",
# page 1, second half
	"Birdman",
	"Maya",
	"EmaSkye",
	"Kristoph G",
	"Trucy",
	"Kay",
	"Miles",
    "Max Payne",
	"Manfred",
	"Franziska",	
# page 2, first half
	"Godot",
	"Klavier",
    "Portsman",
	"Shih-na",
	"Sebastian",
	"Bansai Dragons",
    "Neil",
	"Long Lang",
    "Blackquill",
    "Barnham",
# page 2, second half
	"Darklaw",
	"Barok Z",
	"Gumshoe",
	"Atmey",
	"Daryan Crescend",	
	"Tyrell Badd",
	"Fulbright",
	"Holmes",
	"Butz",
	"Sahwit",
# page 3, first half
	"April",
	"White",
	"WillP",
	"Oldbag",
	"Vasquez",
	"Yanni",
	"Lana",
	"Marshall",
	"Meekins",
	"Angel Starr",	
# page 3, second half	
	"Gant",
	"Maggey",
	"Wellington",
    "Pearl",
	"Max",
	"Moe",
	"Matt",
	"Adrian",
	"AAI Shelly",
	"Dahlia",
# page 4, first half
	"Ron",
	"Furio",	
	"Wocky Kitaki",      
	"Guy",
	"Wesley Stickler",
	"Olga Orly",
	"Vera", 
	"Valant",
	"Rhoda Teneiro",
	"Zinc Lablanc",
# page 4, second half	
	"Cammy",
	"Lauren Paups",
	"Lance Amano",
	"Colias Palaeno",
	"Quercus Alba",
	"Teikan Dragons",
	"Knightley",
	"Simon Clown",
	"Jay Elbird",
	"Tsukasa",
# page 5, first half 
	"Yutaka",
	"Itami_Muto",
	"Shimon",
	"Lbelle",
	"Robin Newman",
	"Juniper",
	"Means",
	"Aura",	
	"Vortex",
	"Gina Lestrade",
# page 5, second half	
	"Crogrey",
    "Leifa Padma Kurain",
	"Hakari",
	"Judge ET",
	"Judge's Bro",
	"Adachi",
	"1 Anonymous",
	"2 Anonymous",
	"3 Anonymous",
	"4 Anonymous",
]