Musiclist = [
	"==AREAS===",
	">Basement",
	">Courtroom 1",
	">Courtroom 2",
	">Courtroom 3",
	">Courtroom 4",
	">Arcade",
	">Lounge",
	"===PRELUDE===",
	"Prelude(AJ).mp3*70",
	"Prelude(AA).mp3*76",
	"Prelude(T&T).mp3*100",
	"Prelude(DD).mp3*160",
	"Prelude(JFA).mp3*89",
	"Prelude(PLvsAA).mp3*180",
	"Prelude(DGS).mp3*114",
	"Prelude(SoJ - Japanifornia).mp3*105",
	"Prelude(SoJ - Khura'in).mp3*148",
	"Prelude(O).mp3*143",
	"Prelude (EC).mp3*89",
	"Prelude(QP).mp3*197",
	"Prelude to The Turnabout.mp3*175",
	"===TRIAL===",
	"Trial(AA).mp3*107",
	"Trial(JFA).mp3*106",
	"Trial(T&T).mp3*141",
	"Trial(T&T) - Special Blend.mp3*61",
	"Trial(AJ).mp3*124",
	"Trial(Miles).mp3*274",
	"Trial(PLvsAA).mp3*204",
	"Trial(PLvsAA) - variation.mp3*122",
	"Trial(PLvsAA) - Final.mp3*140",
	"Trial(PLvsAA - Witch Trial).mp3*113",
	"Trial(DD).mp3*160",
	"Trial(DGS).mp3*196",
	"Trial(SoJ - Japanifornia).mp3*135",
	"Trial(SoJ - Khura'in).mp3*150",
	"Trial(O).mp3*118",
	"Trial(Jazz).mp3*287",
	"Trial (EC).mp3*142",
	"Trial(QP).mp3*135",
	"Omen.mp3*77",
	"Verdict(DGS).mp3*195",
	"===LOGIC===",
	"logic_and_trick.mp3*151",
	"trance_and_logic.mp3*107",
	"trick_and_magic.mp3*74",
	"spirits_and_logic.mp3*78",
	"english_and_logic.mp3*148",
	"Logic ~ The Way to the Truth.mp3*197",
	"Trick Analyze.mp3*125",
	"Trick Break.mp3*155",
	"Tricks and Baroque.mp3*150",
	"Tricks and Gimmicks.mp3*165",
	"Logic Trinity.mp3*114",
	"Logic and Strategy.mp3*64",
	"Theme of Deduction - Beyond the Logic.mp3*135",
	"Captive of Fate.mp3*204",
	"Climax Reasoning.mp3*207",
	"Solve the Puzzle.mp3*193",
	"Solve the Puzzle (PLvsAA).mp3*157",
	"Corpse Logic.mp3*182",
	"Death Logic.mp3*180",
	"Note Logic.mp3*180",
	"Digital Rool.mp3*290",
	"Logic Clarification.mp3*266",
	"Logic and Trick (DGS).mp3*124",
	"Logic and Baroque.mp3*134",
	"Logic and Realization.mp3*283",
	"===SUSPENSE===",
	"Suspence(AA).mp3*91",
	"Suspense(AJ).mp3*48",
	"Suspense (DD).mp3*79",
	"Suspense (EC).mp3*129",
	"Suspense (PLvsAA).mp3*89",
	"Suspense(DGS).mp3*146",
	"Suspense(DGS-variation).mp3*90",
	"Suspense(O).mp3*88",
	"Morphogenetic Sorrow.mp3*297",
	"Fleeting Fate.mp3*273",
	"===CRISIS===",
	"Ultimate Crisis.mp3*130",
	"Stand A Crisis.mp3*129",
	"Crises of Fate.mp3*142",
	"Hotline of Fate.mp3*50",
	"Nuclear Crisis.mp3*187",
	"Thought Route.mp3*112",
	"Thought Route (SoJ).mp3*165",
	"Triffle of Fate.mp3*127",
	"Suspense (DD) (Crisis).mp3*128",
	"Suspense (SoJ) - Crisis.mp3*197",
	"Anguished Court.mp3*81",
	"Trial in Disarray.mp3*176",
	"Strain.mp3*176",
	"===DEBATE / ICE BREAKER===",
	"Reasoning Battle.mp3*147",
	"Reasoning Battle (Allegro).mp3*142",
	"Closing Argument.mp3*168",
	"Joint Reasoning (DGS).mp3*210",
	"Joint Reasoning (Type A).mp3*111",
	"Joint Reasoning (Type B).mp3*112",
	"Joint Reasoning (Type B-2).mp3*127",
	"Joint Reasoning (Type C).mp3*112",
	"The Core.mp3*156",
	"Logic Chess (Opening).mp3*203",
	"Logic Chess (Ending).mp3*191",
	"Logic and Debate.mp3*98",
	"Orchaestral Confrontation.mp3*318",
	"===INVESTIGATION===",
	"Investigation AA (Core).mp3*119",
	"Investigation JFA (Core).mp3*110",
	"Investigation ~ Middle (JFA).mp3*102",
	"Investigation AAI (Core).mp3*164",
	"Investigation AAI2 (Opening).mp3*170",
	"Investigation AAI2 (Middle).mp3*176",
	"Investigation AAI2 (Core).mp3*196",
	"Investigation AJ (Core).mp3*67",
	"Investigation DD (Opening).mp3*123",
	"Investigation DD (Core).mp3*173",
	"Investigation DGS (Opening).mp3*96",
	"Investigation TT.mp3*200",
	"Investigation SoJ (Core - Japanifornia).mp3*152",
	"Investigation SoJ (Opening - Japanifornia).mp3*110",
	"===QUESTIONING===",
	"113 Confrontation ~ Presto 2009.mp3*185",
	"113 Confrontation ~ Presto 2011.mp3*126",
	"Confrontation ~ Moderato 2009.mp3*184",
	"Confrontation ~ Allegro 2009.mp3*206",
	"Confrontation ~ Moderato 2011.mp3*178",
	"Confrontation ~ Allegro 2011.mp3*161",
	"Confrontation Z012 (Moderato).mp3*240",
	"Confrontation Z012 (Allegro).mp3*250",
	"Confrontation Z012 (Presto).mp3*150",
	"Confrontation QP (Moderato).mp3*96",
	"Confrontation QP (Allegro).mp3*103",
	"Questioning AJ (Allegro).mp3*102",
	"Questioning AJ (Moderato).mp3*79",
	"Questioning T&T (Allegro).mp3*159",
	"Questioning T&T (Moderato).mp3*114",
	"Questioning JFA (Allegro).mp3*102",
	"Questioning JFA (Moderato).mp3*88",
	"Questioning DGS (Allegro).mp3*161",
	"Questioning DGS (Moderato).mp3*125",
	"Questioning(AA-allergo).mp3*125",
	"Questioning(AA-normal).mp3*103",
	"Questioning DD (Moderato).mp3*126",
	"Questioning DD (Allegro).mp3*125",
	"Questioning 20X6 (Moderato).mp3*130",
	"Questioning 20X6 (Allegro).mp3*150",
	"Questioning DR (Moderato).mp3*235",
	"Questioning DR (Allegro).mp3*269",
	"Questioning DR (Presto).mp3*269",
	"Questioning GT (Moderato).mp3*72",
	"Questioning GT (Allegro).mp3*69",
	"Questioning PLvsAA (Moderato).mp3*63",
	"Questioning PLvsAA (Allegro).mp3*58",
	"Questioning AA6 (Moderato).mp3*126",
	"Questioning SoJ (Moderato).mp3*130",
	"Questioning SoJ (Allegro).mp3*130",
	"Questioning Z012 (Moderato).mp3*158",
	"Questioning Z012 (Allegro).mp3*226",
	"Questioning (CM) Moderato.mp3*341",
	"Questioning (CM) Allergo.mp3*192",
	"Questioning EC (Moderato).mp3*120",
	"Questioning EC (Allegro).mp3*144",
	"Questioning TT (Moderato).mp3*268",
	"Questioning TT (Allegro).mp3*283",
	"Questioning SJ (Moderato).mp3*69",
	"Questioning SJ (Allegro).mp3*77",
	"Questioning EO (Moderato).mp3*118",
	"Questioning EO (Allegro).mp3*88",
	"Questioning RT (Moderato).mp3*149",
	"Questioning RT (Allegro).mp3*120",
	"Mood Matrix (Moderato).mp3*132",
	"Mood Matrix (Allegro).mp3*123",
	"Percieve - Surging Eyes.mp3*59",
	"Psyche Locks (DD).mp3*84",
	"Water Mirror.mp3*59",
	"Presto (Fairy).mp3*240",
	"Presto (Crown).mp3*293",
	"===OBJECTION===",
	"OBJECTION (SoJ - Athena).mp3*205",
	"OBJECTION (DD - Athena).mp3*162",
	"OBJECTION (SoJ - Apollo).mp3*195",
	"OBJECTION (DD - Apollo).mp3*191",
	"OBJECTION (SoJ - Phoenix).mp3*170",
	"OBJECTION (DD - Phoenix).mp3*141",
	"OBJECTION (DGS).mp3*126",
	"OBJECTION (DGS D).mp3*126",
	"OBJECTION (DGS CS).mp3*170",
	"Objection (DGS - AP).mp3*124",
	"OBJECTION(Miles).mp3*174",
	"Objection (Miles2).mp3*196",
	"OBJECTIOM(AJ).mp3*95",
	"OBJECTION (T&T).mp3*118",
	"OBJECTION (JFA).mp3*92",
	"OBJECTION (AA).mp3*72",
	"OBJECTION (PLvsAA).mp3*155",
	"OBJECTION (DR).mp3*132",
	"OBJECTION (GT).mp3*159",
	"OBJECTION (AA6).mp3*165",
	"OBJECTION (Justice).mp3*315",
	"OBJECTION (EC).mp3*83",
	"OBJECTION (QP).mp3*132",
	"OBJECTION (SJ).mp3*58",
	"OBJECTION (SJ - Nonsense!).mp3*47",
	"OBJECTION (EO).mp3*207",
	"OBJECTION (RT).mp3*100",
	"Objection (FE).mp3*325",
	"Pierce the Heavens.mp3*215",
	"===PURSUIT===",
	"PURSUIT(AA).mp3*95",
	"PURSUIT(AA) - variation.mp3*98",
	"PURSUIT(JFA).mp3*81",
	"PURSUIT(JFA) - variation.mp3*75",
	"PURSUIT(T&T).mp3*119",
	"PURSUIT(T&T) - variation.mp3*113",
	"PURSUIT(T&T) - Rock Remix.mp3*150",
	"PURSUIT 2001(T&T).mp3*89",
	"PURSUIT 2001(T&T) - variation.mp3*82",
	"PURSUIT(AJ).mp3*108",
	"PURSUIT(AJ) - variation.mp3*106",
	"PURSUIT (AAI).mp3*193",
	"PURSUIT (AAI) - variation.mp3*186",
	"PURSUIT(AAI2).mp3*166",
	"PURSUIT(AAI2) - variation.mp3*145",
	"PURSUIT (DD).mp3*151",
	"PURSUIT (DD) - variation.mp3*65",
	"PURSUIT (DD) - variation 2.mp3*140",
	"PURSUIT (PLvsAA).mp3*172",
	"PURSUIT (DGS).mp3*190",
	"PURSUIT (DGS) - variation.mp3*140",
	"PURSUIT (SoJ).mp3*153",
	"PURSUIT (SoJ) - variation.mp3*168",
	"PURSUIT(ASS).mp3*195",
	"PURSUIT(SLAM).mp3*98",
	"PURSUIT (Orchestra).mp3*128",
	"PURSUIT (UMvC3).mp3*242",
	"PURSUIT (AwT).mp3*212",
	"PURSUIT (DR).mp3*172",
	"PURSUIT (SDR).mp3*115",
	"PURSUIT (GT).mp3*119",
	"PURSUIT (PXZ2).mp3*165",
	"PURSUIT (Z012).mp3*182",
	"PURSUIT (Z012) - variation.mp3*170",
	"Pursuit (EC).mp3*104",
	"PURSUIT (QP).mp3*135",
	"PURSUIT (EO).mp3*178",
	"Pursuit(FE).mp3*114",
	"Pursuit(O).mp3*142",
	"Pursuit ~ I Want to Find the Truth(Orchestra).mp3",
	"===RECOLLECTION===",
	"Forgotten Legend.mp3*140",
	"Steel Samurai's Ballad.mp3*130",
	"KG-8 Case.mp3*125",
	"Scars Etched by Flame.mp3*149",
	"Sweet Memories.mp3*67",
	"Wandering Heart.mp3*140",
	"Detention Center (AJ).mp3*214",
	"The Girl's Lost Memories.mp3*181",
	"Viewing the Hazy Bridge.mp3*125",
	"Sleep my Dear.mp3*135",
	"Elegy of Surveillance.mp3*127",
	"Reminiscence - Departure from Regret.mp3*134",
	"True Evening of Grief.mp3*148",
	"The DL6 Incident.mp3*133",
	"Blue Bird's Lamentation.mp3*325",
	"Recollection - Light and Shadow of the Film Studio.mp3*79",
	"Recollection - True Pain.mp3*150",
	"Recollection - The Bitter Taste of Truth.mp3*154",
	"Recollection - A Fate Smeared by Tricks and Gadgets.mp3*131",
	"Recollection - Music Box.mp3*155",
	"===ANNOUNCE THE TRUTH===",
	"Annonce The Truth(DGS).mp3*215",
	"Annonce The Truth(Miles).mp3*151",
	"Annonce The Truth(AJ).mp3*58",
	"Annonce The Truth(T&T).mp3*125",
	"Annonce The Truth(JFA).mp3*97",
	"Annonce The Truth(AA).mp3*78",
	"Annonce The Truth(DR).mp3*282",
	"Annonce The Truth(DD).mp3*129",
	"Annonce The Truth(QP).mp3*163",
	"Confess the Truth (AAI2).mp3*178",
	"Confess the Truth (SoJ).mp3*190",
	"Announce the Truth (PLvsAA).mp3*210",
	"Confess the Truth (EC).mp3*114",
	"===VICTORY CELEBRATION===",
	"Congratulatory People.mp3*65",
	"Moe Congratulatory People.mp3*77",
	"Solution! Calm Moment.mp3*164",
	"Won the Case - Everyones Victory.mp3*110",
	"Victory! - The First Victory.mp3*112",
	"Victory - Inheriting the Purpose.mp3*151",
	"Victory! - The First Victory (EC).mp3*114",
	"Victory! - The Great Turnabout for my Friend.mp3*143",
	"Won the Case - Foreign Victory (SoJ).mp3*208",
	"Journey's End.mp3*138",
	"===CHARACTER THEMES===",
	"Adachi - The Egocentric Police Dick.mp3*66",
	"Apollo Justice - I'm Fine!.mp3*164",
	"Apollo Justice - Nuclear.mp3*302",
	"Asougi Kazuma - Samurai With a Mission.mp3*146",
	"Asougi Kazuma - Nocturne.mp3*170",
	"Athena Cykes- Let's Do This!.mp3*140",
	"Barok van Zieks - Grim Reaper of the Great Court.mp3*254",
	"Bobby Fulbright - Our Secret Word is Justice!.mp3*183",
	"Bonds ~ A Heart That Believes.mp3*218",
	"Caesar Villain - Who Let The Dogs Out.mp3*137",
	"Calisto Yew ~ Let Me Laugh at the Cool.mp3*173",
	"Cammy Meele - Good Niiight.mp3*106",
	"Cabanela - A White Lovely Lanky.mp3*140",
	"Chrom - I Will Not Falter Again.mp3*113",
	"Dahlia Hawthorne - Distant Traces of Beauty.mp3*134",
	"Dane Gustavia ~ Brandished Flavor.mp3*183",
	"Dark Age of the Law.mp3*210",
	"Darklaw - The First Daughter of Labyrinthia.mp3*134",
	"Delia Kartmann ~ Poker Night .mp3*121",
	"Drew Studio.mp3*190",
	"Eccentric (AJ).mp3*100",
	"Eccentric (JFA).mp3*89",
	"Egg Benedict - A Pleasure to Meet You.mp3*120",
	"Ema Skye - Scientific Detective 2016.mp3*205",
	"Ema Skye - Scientific Detective.mp3*85",
	"Ema Skye - Turnabout Sisters.mp3*107",
	"Espella Cantabella - Cursed.mp3*116",
	"Espella Cantabella - The Girl from Labyrinthia.mp3*142",
	"Florent L'Belle - Je Suis L'Belle.mp3*159",
	"Gant - Swimming Anyone.mp3*118",
	"Gina Lestrade - Gunshot from the Downtown.mp3*111",
	"Godot - The Fragrance of Dark Coffee.mp3*147",
	"Great Revival ~ Franziska von Karma.mp3*85",
	"Great Revival ~ Miles Edgeworth.mp3*88",
	"Greater Revival - Miles Edgeworth.mp3*240",
	"Gregoy Edgeworth - A Defense Attorney.mp3*149",
	"Gumshoe - I can do it when it counts.mp3*107",
	"Gumshoe - It's Detective Gumshoe!.mp3*118",
	"Harvey Birdman - Attorney At Law.mp3*84",
	"Hart Vortex - Judge of Time.mp3*170",
	"Hawk - Judge, Jury and Executioner.mp3*165",
	"Horace Knightley - A Knight Protects His King.mp3*230",
	"Inferno Cop - Purgatory Flame.mp3",
	"Jake Marshall ~ Detective From the Wild West.mp3*101",
	"Jay Elbird - Chains Cant Hold a Champion Down.mp3*175",
	"Juniper Woods - Cerulean Woods.mp3*180",
	"Justine Courtney - Goddess of Law.mp3*167",
	"Kitaki Family.mp3*125",
	"Kristoph - Darkness.mp3*107",
	"L - World Class Detective.mp3*170",
	"Lamiroir - Loving Guitar's Serenade.mp3*94",
	"Lewdton - Pursuer of the Lewd Truth.mp3*194",
	"Larry Butz - When Something Smells 2016.mp3*115",
	"Larry Butz - When Something Smells.mp3*117",
	"Lucina - Challenger of Fate.mp3*137",
	"Luke Atmey ~ I Just Want Love.mp3*102",
	"Lynne - A Targeted Redhead.mp3*157",
	"Marvin Grossberg - Old Age, Regret, Retribution.mp3*94",
	"Mask DeMasque ~ Pleeeeease Listen!.mp3*100",
	"Maximillion Galactica - Gorgeous!.mp3*29",
	"Maya Fey - Turnabout Sisters 2016.mp3*158",
	"Maya Fey - Turnabout Sisters 2001.mp3*158",
	"Mikotoba Susato - Blooming Flower in the New World.mp3*150",
	"Missile - A Courageous Little Animal.mp3*116",
	"Olga Orly - Russian Roulette.mp3*168",
	"Orla - Captain Orla's Odyssey.mp3*180",
	"Others ~ Guilty love.mp3*97",
	"Palaeno - Two Embassies.mp3*154",
	"Payne Train - Choo Choo.mp3*165",
	"Pearl Fey ~ With Pearly.mp3*70",
	"Phantom - UNKNOWN.mp3*289",
	"Phoenix Wright - Warehouse Tiger.mp3*103",
	"Professor Layton's Theme ~ VS Arrangement.mp3*90",
	"Prosecutorial Investigation Committee.mp3*195",
	"Robert Snow - Catastrophically Successful Investigator.mp3*133",
	"Robin Newman - I'll give you a P-E-E-K.mp3*138",
	"Rupert Crogrey - Unhand Me, Filthy Urchin!.mp3*120",
	"Rydia - A Dance of Autumn.mp3*250",
	"Q - The Theme of Q.mp3*230",
	"Quercus Alba - The Enemy Who Surpasses the Law.mp3*188",
	"Raymond Shields - Joking Motive.mp3*284",
	"Regina Berry - Circus.mp3*90",
	"Sasha Buckler - Adventures Across the Seven Seas.mp3*165",
	"Sebastian - Debeste Farewell.mp3*151",
	"Sebastian - Debeste Reasoning.mp3*168",
	"Shelly - The Whim of a Murderous Gentleman.mp3*87",
	"Sherlock Holmes - The Great Detective of the Foggy Town.mp3*165",
	"Shimon Aizawa - Pointed Age.mp3*158",
	"Simon Blackquill ~ The Law's Distortion.mp3*130",
	"Simon Keyes - The Man Who Masterminds The Game.mp3*191",
	"Sirhan Dogen - The Tone of an Assassin.mp3*155",
	"Sissel - Sissel's Deal.mp3*96",
	"Speak up, Pup!.mp3*166",
	"The Great Truth Burglar.mp3*147",
	"The Steel Samurai (SoJ).mp3*123",
	"The Steel Samurai.mp3*119",
	"Tobias Gregson - The Enemy of Great Detective.mp3*142",
	"Troupe Gramarye.mp3*111",
	"Tres Bien.mp3*103",
	"Trucy - Child of Jazz.mp3*280",
	"Trucy - Child of Magic.mp3*94",
	"Tsukasa - Sweet Dance.mp3*126",
	"Tyrell Badd - The Truth isn't Sweet.mp3*169",
	"Turnabout Sisters.mp3*112",
	"Turnabout Sisters (Ballad).mp3*115",
	"Victor Kudo ~ Anthem of a Painful Declaration of War.mp3*104",
	"Warden ~ Rock the Outback.mp3*236",
	"Wesley Stickler - Erudite and Panty Enthusiast.mp3*138",
	"Witnesses Enter the Court (DGS).mp3*133",
	"The Final Witness.mp3*188",
	"Yatagarasu ~ The Gentleman Thief Who Dances in the Black Night.mp3*159",
	"Zacharias Barnham - The Sword of Labyrinthia.mp3*160",
	"Zheng Fa - Land of the Phoenix.mp3*216",
	"Zinc White ~ Time is Money.mp3*82",
	"Interesting People.mp3*141",
	"Cowardly People.mp3*207",
	"Desperate People.mp3*167",
	"Doubted People.mp3*175",
	"Elegant People.mp3*97",
	"Intelligent People.mp3*116",
	"Naive People.mp3*90",
	"Noisy People.mp3*90",
	"Philosophical People.mp3*104",
	"Restless People.mp3*154",
	"Russian People.mp3*108",
	"Strange People.mp3*162",
	"Suspicious People.mp3*112",
	"===RELAXING MOMENT===",
	"Also Sprach Brooks.mp3*109",
	"Detective Conan.mp3*150",
	"Godot's Special Blend.mp3*238",
	"guile.mp3*246",
	"Infiltrating the Parisian City Police.mp3*129",
	"Jouji Washington.mp3*102",
	"Procastination.mp3*61",
	"The Lazy Detective Agency.mp3*196",
	"Whose Court is it Anyway.mp3*56",
	"Monochrome.mp3*60",
	"Straight Chaser.mp3*46",
	"In the Speak Easy.mp3*143",
	"A Vision.mp3*76",
	"Roundabout.mp3*509",
	"The Chain.mp3*150",
	"Routine.mp3*176",
	"Life is Beautiful.mp3*183",
	"===MISCALLANEOUS===",
	"3DKH.mp3*289",
	"Ghost Trick - 4 Minutes Before Death.mp3",
	"Ghost Trick - 4 Minutes Before Death (variation).mp3*85",
	"Ghost Trick - Countdown.mp3",
	"Ghost Trick - The World of the Dead.mp3",
	"Ghost Trick - Chicken Paradise.mp3*120",
	"Ghost Trick - Fate Updated.mp3*72",
	"Mystery Skulls - Money.mp3",
	"Trans.mp3*198",
	"ass.mp3",
	"anime.mp3",
	"opening.mp3",
	"opening 2.mp3",
	"Mod Exam - Examination.mp3",
	"Mod Exam - Virtue, Efficiency, Responsibility.mp3",
	"filler.mp3",
	"Heh.mp3",
	"Get well soon Franziska.mp3",
	"You're the inspiration.mp3",
	"sin.mp3",
]